### ISSUE TITLE
Support box-shadow

### ISSUE THREAD

**Issue by yisibl** [ben-eb/postcss-ordered-values#1]
```
box-shadow: inset? && <length>{2,4} && <color>?
```

```css
.foo {
  box-shadow:  2px 5px red;
  box-shadow:  red 2px 5px;
  box-shadow:  2px 5px 10px red;
  box-shadow:  red 2px 5px 10px;
  box-shadow:  inset red 2px 5px 10px;
  box-shadow:  red 2px 5px 10px inset;
  box-shadow:  red 2px 5px 10px inset, blue 2px 5px 10px;
 /* more... */
}
```

:joy: :joy: :joy:
