### ISSUE TITLE
Support transition

### ISSUE THREAD

**Issue by yisibl** [ben-eb/postcss-ordered-values#2]
```
transition: [ none | <single-transition-property> ] || <time> || <single-transition-timing-function> || <time>
```

```css
.foo {
  transition: width .5s ease-out 2s;
  transition: ease-out width .5s 2s;
  transition: ease-out .5s width 2s;
  transition: .5s 2s width ease-out;
  transition: .5s 2s width ease-out, .8s 1s height ease;
 /*  more... */
}
```

:joy: :joy: :joy:
